var coins = [
    { nombre: '-Rial Iraní ', value: 34480 , img:""},
    { nombre: '-Rupi Indonés ', value: 13620, img:""},
    { nombre: '-Won Koreano ', value: 1125, img:"./lib/banderas/SouthKorea.png"},
    { nombre: '-Peso Colombiano ', value: 3019.433, img:"./lib/banderas/Colombia.png"},
    { nombre: '-Peso Chileno ', value: 634.969, img:"./lib/banderas/Chile.png"},
    { nombre: '-Florin Húngaro ', value: 268.185, img:"./lib/banderas/Hungary.png"},
    { nombre: '-Rupi Sri Lanka ', value: 153.549, img:"./lib/banderas/Srilaka.png"},
    { nombre: '-Yen ', value: 113.835, img:"./lib/banderas/China.png"},
    { nombre: '-Rupia India ', value: 65.036, img:"./lib/banderas/India.png"},
    { nombre: '-Rublo Ruso ', value: 58.214, img:"./lib/banderas/Russia.png"},
    { nombre: '-Peso Uruguayo ', value: 29.414, img:"./lib/banderas/Uruguay.png"},
    { nombre: '-Corona Checa ', value: 22.158, img:"./lib/banderas/Czech.png"},
    { nombre: '-Peso Mexicano ', value: 19.144, img:"./lib/banderas/Mexico.png"},
    { nombre: '-Peso Argentino ', value: 17.633, img:"./lib/banderas/Argentina.png"},
    { nombre: '-Randa Sudafricano ', value: 14.179, img:"./lib/banderas/SouthAfrica.png"},
    { nombre: '-Corona Sueca ', value: 8.384, img:"./lib/banderas/Sweeden.png"},
    { nombre: '-Corona Noruega ', value: 8.191, img:"./lib/banderas/Norway.png"},
    { nombre: '-Dólar Hong Kong ', value: 7.803, img:"./lib/banderas/Hongkong.png"},
    { nombre: '-Yuan ', value: 6.65, img:"./lib/banderas/japan.png"},
    { nombre: '-Corona Danesa ', value: 6.426, img:"./lib/banderas/Netherlands.png"},
    { nombre: '-Ringgit Malasio ', value: 4.242, img:"./lib/banderas/Malaysia.png"},
    { nombre: '-Lira Turca ', value: 3.802, img:"./lib/banderas/Turkey.png"},
    { nombre: '-Rial Saudí ', value: 3.751, img:"./lib/banderas/Saudi.png"},
    { nombre: '-Shekel Israeli ', value: 3.686, img:"./lib/banderas/Israel.png"},
    { nombre: '-Dirham Emiratos ', value: 3.673, img:"./lib/banderas/Emirates.png"},
    { nombre: '-Zloty Polaco ', value: 3.666, img:"./lib/banderas/Poland.png"},
    { nombre: '-Real Brasileño ', value: 3.277, img:"./lib/banderas/Brazil.png"},
    { nombre: '-Litas Lituano ', value: 2.934, img:"./lib/banderas/Lithuania.png"},
    { nombre: '-Dólar Neozelandés ', value: 1.457, img:"./lib/banderas/Newzeland.png"},
    { nombre: '-Dólar Singapur ', value: 1.367, img:"./lib/banderas/Singapore.png"},
    { nombre: '-Dólar Canadiense ', value: 1.288, img:"./lib/banderas/Canada.png"},
    { nombre: '-Dólar Americano ', value: 1, img:"./lib/banderas/USA.png"},
    { nombre: '-Franco Suizo ', value: 0.999, img:"./lib/banderas/Switzerland.png"},
    { nombre: '-Euro ', value: 0.864, img:"./lib/banderas/Europe.png"},
    { nombre: '-Libra Inglesa ', value: 0.763, img:"./lib/banderas/UK.png"},
    { nombre: '-Dinar Kuwait ', value: 0.302, img:"./lib/banderas/Kuwait.png"},
    { nombre: '-Ethereum ', value: 0.00321, img:"./lib/banderas/Ethereum.png"},
    { nombre: '-Bitcoin ', value: 0.000167, img:"./lib/banderas/bitcoin.png"},
    {nombre: 'WINNER ', value: 0.00001, img:""}
];

var questions = [
{pregunta:"Que crypto-moneda es mas barata?", respuesta: ["Litecoin", "Dash", "Etherum"]},
{pregunta:"Que crypto-moneda es mas cara?", respuesta:["Ethereum", "Dash", "Ripple"]},
{pregunta:"Cual fue la primer crypto-moneda que se creo?", respuesta:["Bitcoin", "Ethereum", "Litecoin"]},
{pregunta:"Cuanto crees que valía 1 Bitcoin el 1 de enero de 2016? (Hoy vale casi $6000)", respuesta:["$433", "$890", "$2452"]},
{pregunta:"Cual de estas economias creció más durante 2016?", respuesta:["La de India", "La de China", "La de USA" ]},
{pregunta:"El país asiatico que creció más durante 2016 (con un +9.00% del PIB) fue:", respuesta:["Turkmenistán", "Bután", "China" ]},
{pregunta:"La economía mundial que creció más durante 2016 (con un +10.5% del PIB) fue:", respuesta:["Etiopía", "China", "Tanzania"]},
{pregunta:"Cual de estas monedas vale más?", respuesta:["Peso Colombiano", "Won Koreano", "Rupi Indonés" ]},
{pregunta:"Cual de estas monedas es más barata?", respuesta:["Rublo Ruso", "Peso Argentino", "Ringgit Malasio"]},
{pregunta:"El valor de que moneda mundial se depreció un 59% en 2016?", respuesta:["Libra Egipcia", "Rupi Indonéa", "Zloty Polaco" ]},
 ];
