var coins = [
    { nombre: 'Rial Iraní', value: 34480 },
    { nombre: 'Rupi Indonés', value: 13620},
    { nombre: 'Won Koreano', value: 1125},
    { nombre: 'Peso Colombiano', value: 3019.433},
    { nombre: 'Peso Chileno', value: 634.969},
    { nombre: 'Florin Húngaro', value: 268.185},
    { nombre: 'Rupi Sri Lanka', value: 153.549},
    { nombre: 'Yen', value: 113.835},
    { nombre: 'Rupia India', value: 65.036},
    { nombre: 'Rublo Ruso', value: 58.214},
    { nombre: 'Peso Uruguayo', value: 29.414},
    { nombre: 'Corona Checa', value: 22.158},
    { nombre: 'Peso Mexicano', value: 19.144},
    { nombre: 'Peso Argentino', value: 17.633},
    { nombre: 'Randa Sudafricano', value: 14.179},
    { nombre: 'Corona Sueca', value: 8.384},
    { nombre: 'Corona Noruega', value: 8.191},
    { nombre: 'Dólar Hong Kong', value: 7.803},
    { nombre: 'Yuan', value: 6.65},
    { nombre: 'Corona Danesa', value: 6.426},
    { nombre: 'Ringgit Malasio', value: 4.242},
    { nombre: 'Lira Turca', value: 3.802},
    { nombre: 'Rial Saudí', value: 3.751},
    { nombre: 'Shekel Israeli', value: 3.686},
    { nombre: 'Dirham Emiratos', value: 3.673},
    { nombre: 'Zloty Polaco', value: 3.666},
    { nombre: 'Real Brasileño', value: 3.277},
    { nombre: 'Litas Lituano', value: 2.934},
    { nombre: 'Dólar Neozelandés', value: 1.457},
    { nombre: 'Dólar Singapur', value: 1.367},
    { nombre: 'Dólar Canadiense', value: 1.288},
    { nombre: 'Dólar Americano', value: 1},
    { nombre: 'Franco Suizo', value: 0.999},
    { nombre: 'Euro', value: 0.864},
    { nombre: 'Libra Inglesa', value: 0.763},
    { nombre: 'Dinar Kuwait', value: 0.302},
    { nombre: 'Ethereum', value: 0.00321},
    { nombre: 'Bitcoin', value: 0.000167}
];

var questions = [
{pregunta:"Que crypto-moneda es mas barata?", respuesta: ["Litecoin", "Dash", "Etherum"]},
{pregunta:"Que crypto-moneda es mas cara?", respuesta:["Ethereum", "Dash", "Ripple"]},
{pregunta:"Cual fue la primer crypto-moneda que se creo?", respuesta:["Bitcoin", "Ethereum", "Litecoin"]},
{pregunta:"Cuanto crees que valía 1 Bitcoin el 1 de enero de 2016? (Hoy vale casi $6000)", respuesta:["$433", "$890", "$2452"]},
{pregunta:"Cual de estas economias creció más durante 2016?", respuesta:["La de India", "La de China", "La de USA" ]},
{pregunta:"El país asiatico que creció más durante 2016 (con un +9.00% del PIB) fue:", respuesta:["Turkmenistán", "Bután", "China" ]},
{pregunta:"La economía mundial que creció más durante 2016 (con un +10.5% del PIB) fue:", respuesta:["Etiopía", "China", "Tanzania"]},
{pregunta:"Cual de estas monedas vale más?", respuesta:["Peso Colombiano", "Won Koreano", "Rupi Indonés" ]},
{pregunta:"Cual de estas monedas es más barata?", respuesta:["Rublo Ruso", "Peso Argentino", "Ringgit Malasio"]},
{pregunta:"El valor de que moneda mundial se depreció un 59% en 2016", respuesta:["Libra Egipcia", "Rupi Indonéa", "Zloty Polaco" ]},
 ];
