var coins = [
    { nombre: '-Iranian Rial ', value: 34480 , img:""},
    { nombre: '-Indonesian Rupi ', value: 13620, img:""},
    { nombre: '-Korean Won ', value: 1125, img:"./lib/banderas/SouthKorea.png"},
    { nombre: '-Colombian Peso ', value: 3019.433, img:"./lib/banderas/Colombia.png"},
    { nombre: '-Chilean Peso ', value: 634.969, img:"./lib/banderas/Chile.png"},
    { nombre: '-Hungarian Florin ', value: 268.185, img:"./lib/banderas/Hungary.png"},
    { nombre: '-Sri Lankas Rupi ', value: 153.549, img:"./lib/banderas/Srilaka.png"},
    { nombre: '-Yen ', value: 113.835, img:"./lib/banderas/China.png"},
    { nombre: '-Indian Rupia  ', value: 65.036, img:"./lib/banderas/India.png"},
    { nombre: '-Russian Ruble ', value: 58.214, img:"./lib/banderas/Russia.png"},
    { nombre: '-Uruguayan Peso ', value: 29.414, img:"./lib/banderas/Uruguay.png"},
    { nombre: '-Czeck Koruna ', value: 22.158, img:"./lib/banderas/Czech.png"},
    { nombre: '-Mexican Peso ', value: 19.144, img:"./lib/banderas/Mexico.png"},
    { nombre: '-Argentinian Peso', value: 17.633, img:"./lib/banderas/Argentina.png"},
    { nombre: '-Southafrican Randa ', value: 14.179, img:"./lib/banderas/SouthAfrica.png"},
    { nombre: '-Sweedish Koruna ', value: 8.384, img:"./lib/banderas/Sweeden.png"},
    { nombre: '-Norwegian Koruna ', value: 8.191, img:"./lib/banderas/Norway.png"},
    { nombre: '-Hong Kong Dollar', value: 7.803, img:"./lib/banderas/Hongkong.png"},
    { nombre: '-Yuan ', value: 6.65, img:"./lib/banderas/japan.png"},
    { nombre: '-Dutch Koruna ', value: 6.426, img:"./lib/banderas/Netherlands.png"},
    { nombre: '-Malassian Ringgit ', value: 4.242, img:"./lib/banderas/Malaysia.png"},
    { nombre: '-Turkish Lira ', value: 3.802, img:"./lib/banderas/Turkey.png"},
    { nombre: '-Saudí Rial', value: 3.751, img:"./lib/banderas/Saudi.png"},
    { nombre: '-Israel Shekel', value: 3.686, img:"./lib/banderas/Israel.png"},
    { nombre: '-Emirates Dirham', value: 3.673, img:"./lib/banderas/Emirates.png"},
    { nombre: '-Polish Zloty ', value: 3.666, img:"./lib/banderas/Poland.png"},
    { nombre: '-Brasilian Real ', value: 3.277, img:"./lib/banderas/Brazil.png"},
    { nombre: '-Lithuanian Litas ', value: 2.934, img:"./lib/banderas/Lithuania.png"},
    { nombre: '-Newzeland Dollar ', value: 1.457, img:"./lib/banderas/Newzeland.png"},
    { nombre: '-Singapore Dollar ', value: 1.367, img:"./lib/banderas/Singapore.png"},
    { nombre: '-Canadian Dollar ', value: 1.288, img:"./lib/banderas/Canada.png"},
    { nombre: '-US Dollar ', value: 1, img:"./lib/banderas/USA.png"},
    { nombre: '-Swiss Franc ', value: 0.999, img:"./lib/banderas/Switzerland.png"},
    { nombre: '-Euro ', value: 0.864, img:"./lib/banderas/Europe.png"},
    { nombre: '-English Pound ', value: 0.763, img:"./lib/banderas/UK.png"},
    { nombre: '-Kuwaits Dinar ', value: 0.302, img:"./lib/banderas/Kuwait.png"},
    { nombre: '-Ethereum ', value: 0.00321, img:"./lib/banderas/Ethereum.png"},
    { nombre: '-Bitcoin ', value: 0.000167, img:"./lib/banderas/bitcoin.png"},
    {nombre: 'WINNER ', value: 0.00001, img:""}
];

var questions = [
{pregunta:"Which cryptocurrency is cheaper?", respuesta: ["Litecoin", "Dash", "Etherum"]},
{pregunta:"Which cryptocurrency is the most expensive?", respuesta:["Ethereum", "Dash", "Ripple"]},
{pregunta:"The first cryptocurrency was:", respuesta:["Bitcoin", "Ethereum", "Litecoin"]},
{pregunta:"How much was 1 Bitcoin worth in Jan 2016 (today is close to $6000)", respuesta:["$433", "$890", "$2452"]},
{pregunta:"Which economy grew more in 2016?", respuesta:["India's", "China's", "USA" ]},
{pregunta:"The Asian experienced the largest economic growth? (+9.00% of GDP)", respuesta:["Turkmenistan", "Butane", "China" ]},
{pregunta:"The world economy that grew the most in 2106 (with +10.09% rise in GDP) was:", respuesta:["Iraq", "China", "Tanzania"]},
{pregunta:"Which currency has the highest value?", respuesta:["Colombian Peso", "Korean Won", "Indonesian Rupi" ]},
{pregunta:"Which currency is the cheapest?", respuesta:["Russian Ruble", "Argentinian Peso", "Malassian Ringgit"]},
{pregunta:"Which currency depreciated 59% in 2016?", respuesta:["Egypcian Pound", "Indonesian Rupi", "Polish Zloty" ]},
{pregunta:"Which currency is the cheapest?", respuesta:["US Dollar", "Swiss Franc", "Euro" ]},
{pregunta:"Which economy grew more in 2016?", respuesta:["Spain's", "Germany's", "Austrailia's" ]},
{pregunta:"Yemen's GDP fell by _% in 2016", respuesta:["28%", "12%", "55%" ]},
{pregunta:"Which currency has the highest value?", respuesta:["Canadian Dollar", "Singapore Dollar", "Brasilian Real" ]},
{pregunta:"Which country has the most expensive currency in the world?", respuesta:["Kuwait", "Germany", "UK" ]},
{pregunta:"Which country has the highest robot density in the world?", respuesta:["South Korea", "Japan", "Germany" ]},
{pregunta:"The beauty of me, is tha im very rich. Who said this?", respuesta:["Trump", "Jeff Bezos", "Putin" ]},
{pregunta:"Apple's market cap is?", respuesta:["756 billion", "1 trillion", "560 billion" ]}

 ];
